services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - ./images:/app/public/images
    command: npm run dev

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./images:/images
    command: watchmedo auto-restart --directory=. --pattern="*.py" --recursive -- python app.py
